title: 'Vadim Titko'
tagline: 'Blog'
paginate: 5
permalink: pretty


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
domain: localhost:4000
url: http://localhost:4000
baseurl: ''
source: ./source
