plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
repository: Vadbeg/vtitko-blog.github.io
domain: vadbeg.github.io     # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
