plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
repository: Vadbeg/vtitko-blog.github.io
domain: vadbeg.github.io     # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://vadbeg.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /vtitko-blog.github.io/      # place folder name if the site is served in a subfolder
